---
exp_dir: experiment_files/
seed: 123

model:
  name: AGE
  hidden_size: 128
  encoder:
    num_layers: 6
    num_attn_heads: 8
    dim_feedforward: 1024
    dropout: 0.2
  decoder:
    num_layers: 6
    num_attn_heads: 2
    dim_feedforward: 1024
    dropout: 0.2

experiment:
  gpus: [0]
  train:
    batch_size: 16
    num_workers: 4
    shuffle_data: True
    epochs: 10000
    optimizer: Adam
    lr: 0.001
    cycle_len: 75
    lr_decay: 0.3
    weight_decay: 0.0002
    label_smoothing: 0.00
    prev_edge_smoothing: 0.1
    milestones: [250, 750]
    snapshot_epochs: 50
    display_iters: 10
    es_improvement_len: 8000
    clip_grad: 3
    use_writer: False
  validation:
    es_buffer: 100  # Burn in period for early stopping
    val_p: 0.2  # Proportion of TRAINING data to use for validation
    val_epochs: 5  # Interval between validation epochs
    es_patience: 20  # How many times to validate with no improvement before stopping
    batch_size: 10000
  test:
    batch_size: 32
    loader: GNNTestSampler
